version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MYSQLHOST=containers-us-west-201.railway.app
      - MYSQLUSER=root
      - MYSQLPASSWORD=oWNPKISixOPZyqDKNMIOrYXbFYWsGRXb
      - MYSQLDATABASE=railway
      - MYSQLPORT=3306
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mommom_food_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: mommom_food
      MYSQL_USER: mommom_food
      MYSQL_PASSWORD: 1
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mommom_food_phpmyadmin
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - "8844:80"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
